apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  volumes:
    - name: task2-pv-storage
      persistentVolumeClaim:
        claimName: task2-pv-claim
  containers:
    - name: task-pv-conatiner
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/app/config"
          name: task2-pv-storage
  nodeName: k8s-control

